name: 'Setup Java and Maven'
description: 'Setup Java and Maven for pipeline'
inputs:
  github-token:
    description: 'Token used to reach maven.pkg.github.com'
    required: true
  java-version:
    description: 'Java SDK version to use'
    required: false
    default: '21'
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.9.5'
runs:
  using: "composite"
  steps:
    - name: Set up JDK-${{ inputs.java-version }} with cache
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # ratchet:actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
        server-password: ${{ inputs.github-token }}
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: ${{ inputs.maven-version }}
