version: 2
updates:
  - package-ecosystem: github-actions
    directory: ".github/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 10
    registries:
      - github
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }} # dependabot secret
