name: "Build and push docker image"
description: "Build and push docker image"
inputs:
  build-version:
    description: "Image tag for the docker image"
    required: true
  github-token:
    description: "Token to use when signing into ghcr.io"
    required: true
  push-image:
    required: false
    description: "Push the docker image to gchr.io (true|false)"
    default: "false"
  bake-action:
    required: false
    description: "Use docker bake action to build and push"
    default: "false"
  bake-platform:
    required: false
    type: string
    description: Platform to target
    default: ""
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      if: inputs.bake-action == 'false'
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        pull: true
        push: ${{ inputs.push-image == 'true' }}
        tags: ghcr.io/${{ github.repository }}:${{ inputs.build-version }}, ghcr.io/${{ github.repository }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Cache Docker layers
      if: inputs.bake-action == 'true'
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.bake-platform }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.bake-platform }}-
          ${{ runner.os }}-buildx-

    - name: Build and push with bake
      if: inputs.bake-action == 'true'
      uses: docker/bake-action@v3.0.1
      env:
        TAG: ${{ inputs.bake-platform }}-${{ github.sha }}
      with:
        # push: ${{ inputs.push-image == 'true' }}
        push: true
        set: |
          *.platform=linux/${{ inputs.bake-platform }}
          *.cache-from=type=local,src=/tmp/.buildx-cache
          *.cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max

    - # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      shell: bash
      if: inputs.bake-action == 'true'
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
