name: Build app

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: Miljø versjon som skal brukes til bygg.
        default: 'ubuntu-latest'
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '17'
      use-oracle:
        required: false
        type: boolean
        description: Skal oracle database brukes?
        default: true
      sonar-scan:
        required: false
        type: boolean
        description: Skal sonar scan brukes?
        default: false
      push:
        required: false
        type: boolean
        description: Skal docker image pushes
        default: false
    outputs:
      build-version:
        description: "Build version"
        value: ${{ jobs.build-and-test.outputs.build-version }}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ${{ inputs.runs-on }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: fpabakus_unit
          POSTGRES_PASSWORD: fpabakus_unit
          POSTGRES_DB: fpabakus_unit
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      TZ: "Europe/Oslo"
    outputs:
      build-version: ${{ steps.generate-build-version.outputs.build-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
        with:
          fetch-depth: 0

      - name: Create maven .m2 settings
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{
              "id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }
            }]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
          output_file: settings.xml

      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate build version
        id: generate-build-version
        run: |
          echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Print build version
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and start Oracle database
        if: inputs.use-oracle
        id: oracle
        run: |
          echo "Henter og starter Oracle image"
          cd .oracle
          docker-compose up --quiet-pull > nohup.out 2>&1 &
          sh -c 'tail -n +0 -f nohup.out | { sed "/Database opened./q" && kill $$; }' || true
          echo "db-port=${{ job.services.oracle.ports[1521]}}" >> $GITHUB_OUTPUT

      - name: Build with multithreading
        run: |
          echo "Runs-on=${{ inputs.runs-on }}"
          if ! [[ $inputs.runs-on =~ ^ubuntu-latest$ ]]; then
            echo "threads-tag=$(echo '-T 2C' )" >> $GITHUB_ENV
          fi
          echo "Generated thread-tag = $threads-tag"

      - name: Setup postgres
        if: (!inputs.use-oracle)
        run: |
          echo "db-port=${{ job.services.postgres.ports[5432]}} " >> $GITHUB_OUTPUT

      - name: Build artifacts without sonar
        if: (!inputs.sonar-scan || github.actor == 'dependabot[bot]')
        run: |
          echo "Building artifacts ${{ steps.generate-build-version.outputs.build-version }}"
          mvn versions:set -DnewVersion="${{ steps.generate-build-version.outputs.build-version }}" -s settings.xml
          mvn verify -s settings.xml $threads-tag -q -e -B -Dfile.encoding=UTF-8
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ env.db-port }}

      - name: Build artifacts with sonar
        if: (inputs.sonar-scan && github.actor != 'dependabot[bot]')
        run: |
          echo "Building artifacts ${{ steps.generate-build-version.outputs.build-version }}"
          mvn versions:set -s settings.xml -DnewVersion="${{ steps.generate-build-version.outputs.build-version }}"
          mvn jacoco:prepare-agent install jacoco:report -s settings.xml $threads-tag -e -q -B -Djacoco.destFile=$(pwd)/target/jacoco.exec -Dfile.encoding=UTF-8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ env.db-port }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          pull: true
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.generate-build-version.outputs.build-version }}, ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
