name: Deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Image navn"
      cluster:
        required: true
        type: string
        description: "The cluster to deploy to."
      namespace:
        required: false
        type: string
        description: "The namespace to deploy to."
        default: "teamforeldrepenger"
      app:
        required: true
        type: string
        description: "The app to deploy."
env:
  IMAGE: ${{ inputs.image }} # Brukes i naiserator.yaml
jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.cluster }}:${{ inputs.app }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # ratchet:actions/checkout@v4
      - name: Deploy ${{ inputs.cluster }}
        uses: nais/deploy/actions/deploy@b2c5fbf3fc4d777a36b311da70d9ff429416b552 # ratchet:nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/${{ inputs.app }}/${{ inputs.cluster }}-${{ inputs.app }}.json
