name: Slash command dispatch

on:
  workflow_call:

jobs:
  dispatch:
    name: Dispatch
    runs-on: 'ubuntu-latest'
    steps:
      - name: Slash command dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          commands: promote # matcher repository dispatch med navent 'promote-command'
          issue-type: issue
          allow-edits: true
