name: Maintain issues

on:
  workflow_call:
    inputs:
      build-version:
        required: true
        type: string
        description: 'Build version of the produced image.'
    outputs:
      issue-number:
        description: "Created issue number"
        value: ${{ jobs.maintain-issues.outputs.issue-number }}

jobs:
  maintain-issues:
    name: Maintain issues
    runs-on: 'ubuntu-latest'
    env:
      TZ: "Europe/Oslo"
    outputs:
      issue-number: ${{ steps.create-deploy-issue.outputs.issue-number }}
    steps:
      - name: Lukk gamle deployment-issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['deployment']
            }).then(response => {
              response.data.forEach(issue => {
                github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });

      -  name: Opprett deployment issue
         if: success()
         id: create-deploy-issue
         uses: actions/github-script@v6
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             github.rest.issues.create( {
               owner: context.issue.owner,
               repo: context.issue.repo,
               labels: ['deployment'],
               title: 'Deploy av ${{ inputs.build-version }}',
               body: '${{ github.sha }}'})
             .then(response => {
                     core.setOutput('issue-number', response.data.number);
              });
