name: Release feature

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        description: 'The release version.'
      java-version:
        required: false
        type: string
        description: 'Java SDK versjon som skal brukes.'
        default: '17'
      mvn-projects:
        required: false
        type: string
        description: 'Comma-delimited list of specified reactor projects to build instead of all projects.'
        default: ''
      release-profiles:
        required: false
        type: string
        description: 'Profiles which should be used when releasing an artifact.'
        default: '-Pdeploy'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Setup java and maven
        uses: navikt/fp-gha-workflows/.github/actions/setup-java-maven@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}

      - name: Publish artifacts
        run: |
          mvn -B -s settings.xml versions:set -DnewVersion=${{ inputs.release-version }}
          mvn -B -s settings.xml -DskipTests clean deploy ${{ inputs.mvn-projects }} ${{ inputs.release-profiles }}
